apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
spec:
  replicas: 5
  selector:
      matchLabels:
          app: my-app1
  template:
      metadata:
          labels:
              app: my-app1
      spec:
          containers:
          - name: nginx
            image: nginx