apiVersion: v1
kind: Service
metadata:
  name: azure-vote-plus-front
  labels:
    app: azure-vote-plus
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    component: azure-vote-plus-front