apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-plus-back
  labels:
    app: azure-vote-plus
spec:
  replicas: 1
  selector:
    matchLabels:
      component: azure-vote-plus-back
  template:
    metadata:
      labels:
        app: azure-vote-plus
        component: azure-vote-plus-back
    spec:
      containers:
        - name: azure-vote-back
          image: redis
          ports:
            - containerPort: 6379
              name: redis