apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-plus-front
  labels:
    app: azure-vote-plus
spec:
  replicas: 2
  selector:
    matchLabels:
      component: azure-vote-plus-front
  template:
    metadata:
      labels:
        app: azure-vote-plus
        component: azure-vote-plus-front
    spec:
      containers:
        - name: azure-vote-front
          image: microsoft/azure-vote-front:v1
          ports:
            - containerPort: 80
          env:
            - name: REDIS
              value: "azure-vote-plus-back"